name: newsblog_prokit
description: Guide AtoZ Project.
version: 1.0.1+3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^10.0.2
  flutter_launcher_icons: "^0.10.0"

  # Base
  cupertino_icons: ^1.0.4
  nb_utils: ^4.4.10
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0
  google_fonts: ^2.2.0
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1

  #News Blog
  cached_network_image: ^3.1.0
  url_launcher: ^6.0.3
  image_picker: ^0.8.1+3
  path_drawing: ^0.5.1+1

  speech_to_text: ^6.1.0
  highlight_text: ^0.7.2
  avatar_glow: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true
  assets:
    - images/

flutter_icons:
  android: true
  ios: true
  image_path: "images/guide_logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/guide_logo.jpg"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "images/guide_logo.jpg"
    icon_size: 48 # min:48, max:256, default: 48
